config/routes.rb
Rails.application.routes.draw do
  
get 'payments/new'
get 'payments/receipt'

  get 'static_pages/welcome'

  resources :listings
  resources :users
  resources :reservations do
    resources :payments, only: [:new, :create]
  end

  

  root 'static_pages#welcome'
  get 'user_listings' => 'listings#user_listings'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	
	mount_uploaders :showrooms, ShowroomUploader

	belongs_to :user
	has_many :reservations
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
    # @listing = current_user.listings
  end

  def user_listings
    @listings = current_user.listings
  end 

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)
    # @listing = Listing.new(listing_params)
      #@listing = creating new listing
      #current_user refering to current user that logged in now
      #listing: because one user may have many listings so 
      #among the listings there create one @listing object

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:user_id, :description, :accomodates, :address, 
        :city, :price, :smoking_room, :pet_friendly, :apartment, :house, {showrooms: []})
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Showroom %><br>
    <%= f.file_field :showrooms, multiple: true %>
  </div>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :accomodates %><br>
    <%= f.text_field :accomodates %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :smoking_room %><br>
    <%= f.check_box :smoking_room %>
  </div>
  <div class="field">
    <%= f.label :pet_friendly %><br>
    <%= f.check_box :pet_friendly %>
  </div>
  <div class="field">
    <%= f.label :apartment %><br>
    <%= f.check_box :apartment %>
  </div>
  <div class="field">
    <%= f.label :house %><br>
    <%= f.check_box :house %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listings</h1>

<table>
  <thead>
    <tr>
      <th>Showroom</th>
      <th>User</th>
      <th>Description</th>
      <th>Accomodates</th>
      <th>Address</th>
      <th>City</th>
      <th>Price</th>
      <th>Smoking room</th>
      <th>Pet friendly</th>
      <th>Apartment</th>
      <th>House</th>
      <th>Show</th>
      <th>Book Your Reservation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
        <td><% listing.showrooms.each do |showroom| %>
          <%= image_tag showroom.url, height: 80, width: 80 %> 
          <% end %>
        </td>
        <td><%= listing.user_id %></td>
        <td><%= listing.description %></td>
        <td><%= listing.accomodates %></td>
        <td><%= listing.address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.price %></td>
        <td><%= listing.smoking_room %></td>
        <td><%= listing.pet_friendly %></td>
        <td><%= listing.apartment %></td>
        <td><%= listing.house %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Boow Now', new_reservation_path + '?id=' + listing.id.to_s %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %><br>
<br>

 <%= link_to 'Your Listings', user_listings_path %><br>
<br>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Showroom</strong>
  <% @listing.showrooms.each do |showroom| %>
    <%= image_tag showroom.url, height: 80, width: 80 %>   
    <% end %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Accomodates:</strong>
  <%= @listing.accomodates %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Smoking room:</strong>
  <%= @listing.smoking_room %>
</p>

<p>
  <strong>Pet friendly:</strong>
  <%= @listing.pet_friendly %>
</p>

<p>
  <strong>Apartment:</strong>
  <%= @listing.apartment %>
</p>

<p>
  <strong>House:</strong>
  <%= @listing.house %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/listings/user_listings.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Description</th>
      <th>Accomodates</th>
      <th>Address</th>
      <th>City</th>
      <th>Price</th>
      <th>Smoking room</th>
      <th>Pet friendly</th>
      <th>Apartment</th>
      <th>House</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
        <td><% listing.showrooms.each do |showroom| %>
          <%= image_tag showroom.url, height: 80, width: 80 %> 
          <% end %>
        </td>
        <td><%= listing.user_id %></td>
        <td><%= listing.description %></td>
        <td><%= listing.accomodates %></td>
        <td><%= listing.address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.price %></td>
        <td><%= listing.smoking_room %></td>
        <td><%= listing.pet_friendly %></td>
        <td><%= listing.apartment %></td>
        <td><%= listing.house %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>