config/routes.rb
Rails.application.routes.draw do
  
get 'payments/new'
get 'payments/receipt'

  get 'static_pages/welcome'

  resources :listings
  resources :users
  resources :reservations do
    resources :payments, only: [:new, :create]
  end

  

  root 'static_pages#welcome'
  get 'user_listings' => 'listings#user_listings'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	has_many :users
	has_many :payments
	belongs_to :listing

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])

  end

  def new
    @reservation = Reservation.new
    # @listing = Listing.find(params[:id])
  end

  def edit
  end

  def create
    
    @reservation = current_user.reservations.new(reservation_params)
    @listing = Listing.find(params[:reservation][:listing_id])
    @reservation.listing_id = @listing.id
    @reservation.total_price = @reservation.listing.price.to_i*(@reservation.end_date - @reservation.start_date)
    

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
  end

  def destroy
  end


 private
    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for @reservation do |f| %>

  <div class="form-group">
    <%= f.label :check_in %>
    <%= f.date_select :start_date, :order => [:day, :month, :year]%>
  </div>

  <div class="form-group">
    <%= f.label :check_out %>
    <%= f.date_select :end_date, :order => [:day, :month, :year] %>
  </div>


  <div class="field">
 	  <%= f.hidden_field "listing_id", value: params[:id] %><br>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/new.html.erb
<h1>Please make reservations</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

<p>Your Total Payment</p>
<p>$<%= @reservation.total_price.to_i %></p><br>

<%= link_to 'Pay Now', new_reservation_payment_path(@reservation.id), data: {no_turbolink: true} %>

<%= link_to 'Back', reservation_path %>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>