config/routes.rb
Rails.application.routes.draw do
  
get 'payments/new'
get 'payments/receipt'

  get 'static_pages/welcome'

  resources :listings
  resources :users
  resources :reservations do
    resources :payments, only: [:new, :create]
  end

  

  root 'static_pages#welcome'
  get 'user_listings' => 'listings#user_listings'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :reservation
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # before_action do_some_security_activity_available, only: [:new, :create]
  def index
  end

  def new
    @client_token = Braintree::ClientToken.generate
    @reservation = Reservation.find(params[:reservation_id])
    @payment = Payment.new
  end

  def create
    @reservation = Reservation.find(params[:reservation_id])
    nonce = params[:payment_method_nonce]
    render action: :new and return unless nonce
    result = Braintree::Transaction.sale(
      amount:  @reservation.total_price.to_i,
      payment_method_nonce: params[:payment_method_nonce]
    )
    byebug

    # reserve to save the transaction details into database 
    redirect_to reservations_path
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private 
  def generate_client_token
    Braintree::ClientToken.generate
  
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/destroy.html.erb
<h1>Payments#destroy</h1>
<p>Find me in app/views/payments/destroy.html.erb</p>

app/views/payments/edit.html.erb
<h1>Payments#edit</h1>
<p>Find me in app/views/payments/edit.html.erb</p>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<p>Testing 123</p>

<%= form_for(@payment, url: reservation_payments_path) do |f| %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= @reservation.start_date %><br>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= @reservation.end_date %><br>
  </div>
  <div class="field">
    <%= f.hidden_field :reservation_secure_token, value: @reservation.secure_token %><br>
  </div>
  <div class="field">
    <div id="dropin"></div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<script type="text/javascript">
  function setupBT() {
    braintree.setup("<%= @client_token %>", 'dropin', {
      container: 'dropin'
    });
  }

  if (window.addEventListener)
    window.addEventListener("load", setupBT, false);
  else if (window.attachEvent)
    window.attachEvent("onload", setupBT);
  else window.onload = setupBT;

</script>

app/views/payments/show.html.erb
<h1>Payments#show</h1>
<p>Find me in app/views/payments/show.html.erb</p>

app/views/payments/update.html.erb
<h1>Payments#update</h1>
<p>Find me in app/views/payments/update.html.erb</p>